[project]
name = "instru_package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gino", email = "7114065027@smail.nchu.edu.tw" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "nidaqmx>=1.6.0",
    "pandas>=3.0.6",
    "pyserial>=3.5",
    "pyvisa>=1.16.2",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
instru_package = "instru_practice:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
